# Site settings
title: Raymond Tsang
twitter_username: RayTsangHK
name: Raymond Tsang

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Facebook
   url: https://www.facebook.com/tsangkeiman/
 - title: GitHub
   url: https://github.com/raytsang
 - title: LinkedIn
   url: https://www.linkedin.com/in/raymond-tsang-159290119/

#Any buzzword skills you want to include
skills:
 - Unity 3D
 - Visual C#
 - Visual C++
 - MySQL
 - Node.js
 - PHP
 - Java

#Work experience is required
roles:
 - title: Project Manager / Development Lead
   start: Feb 2017
   end: Ongoing
   employer: Skytree Digital Limited
   description: It is a company with both app and game development. I am the project manager of game team. I am responsible for all the planning and scheduling of the whole project with server/client side of development. We use Unity3D with C# script as a game engine to develop the games.
 - title: Development Lead
   start: Aug 2016
   end: Jan 2017
   employer: Mad Head App Limited
   description: This company is one of the top company in game industry. I am responsible for the client side of game development. I need to schedule the tasks for me and the junior programmers. We use Unity3D with C# script as a game engine to develop some mobile games.
 - title: Senior Software Engineer
   start: Dec 2015
   end: Jul 2016
   employer: Hang Seng Management College
   description: My duty is to design and develop a platform for instructors to create some business games. The platform is developed by Java and using oracle database. The platform also use some realistic company data from SAP A1, which is a ERP program, to be the game data.
 - title: Technical Manager
   start: March 2007
   end: Nov 2015
   employer: Gamemiracle
   description: Gamemiracle is a game developing company since 2004. I am a programmer working in game industry. I need to program the game flow and game logic. All the graphic user interface arrangement. Artificial intelligence is designed if needed. Manage the database in order to store the data of user.

#Education is required
education:
 - level: Master of Philosophy (M.Phil)
   date: 2006
   subject: Computer Science
   school: Hong Kong University of Science & Technology
 - level: Bachelor of Engineering  (B.Eng.)
   date: 2004
   subject: Computer Engineering
   school: Hong Kong University of Science & Technology
 
#Mobile apps section is optional
apps:
 - name: 億萬遺跡
   platform: iOS and Android
   url: https://itunes.apple.com/hk/app/%E5%84%84%E8%90%AC%E9%81%BA%E8%B7%A1/id1369877100?mt=8
   description: Monopoly game using cards

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   I would love to work in an innovative and challenging environment. During my study, I have been very hardworking to get an outstanding performance. I am an eager learner and willing to face any problems and difficulties without hesitation.
